### ISSUE TITLE
[1.4.0 Beta 3] keys unresponsive after boot

### ISSUE THREAD

**Issue by aheger** [polyend/TrackerIssues#1132]
### Steps to reproduce

Installed 1.4.0 Beta 3.  
Unit boots normally into Pattern screen. Keys are totally unresponsive.  
The data knob works. The pads light up. Other keys do nothing.  

Resetting back to Beta 2 fixes the problem.

**Comment by PITmast** [comment]
Is it possible to go back to Beta 2 with keys issue?

**Comment by aheger** [comment]
> Is it possible to go back to Beta 2 with keys issue?

I used the Reset-Button to get back to Beta2. See: https://github.com/polyend/TrackerIssues/blob/master/HOWTO_BETA_FIRMWARE.md

**Comment by PITmast** [comment]
Anybody else can confirm keys issue?
I want to test Beta 3 but can’t use Polyend Tool in case of problems due to Mac OS version.

Regards
Piotr

**Comment by k4ot** [comment]
Had a similar problem with 1.3.1 while I was in the sample loader. It bugged, then every square key was KO.
Light leads OK, jog OK, power button OK, but not one square plastic key was working anymore.
Somehow a reboot doesn't fix the issue.
Only fix is to unplug power cord and plug it again.

To me it looks like a software bug that became hardware bug. The fact the bug is reboot-proof is very strange. 
I asked on PT if someone had the problem. No one.

I RMA'ed the PT.

**Comment by bndofc** [comment]
i recently had this happen on 1.4.0b2, don't know under what circumstances it occurred. indeed the only way was to fix it was by unplugging it

**Comment by PITmast** [comment]
I have no keys issue with 1.4.0 Beta 3.
Looks like #1115 and #1098 are fixed.
Thank you Poly for this update.

Regards
