### ISSUE TITLE
[1.4] Losing songs after 100 in the Projects folder

### ISSUE THREAD

**Issue by imehesz** [polyend/TrackerIssues#1253]
### Steps to reproduce

Save more than 100 songs.

When you have more than 100 songs in the Projects folder, in the `Files` view, the tracker won't display them (only the first 100) 
The files are on the SD card, please see attachment.

### Attachments and links

![242489887_10226448095845959_4028362787679342240_n](https://user-images.githubusercontent.com/13553/134447703-03d980fd-6e86-417e-a3b7-548d71983410.jpg)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

every time

* Does this bug happen in previous firmware versions?

yes (I just upgraded to the latest one)

* Does this bug happen in every project?

yes

**Comment by manuel12374** [comment]
The same limitations applies to all file management across all folders: i’ve tested a d got the same limitations for example when reading the MOD folder: while in the SD card in the mod folder i have 550+ files, the file manager shows only the top 100 and the only way to load the 101 one is to delete one of the top 100. if the 100 girls is an hard limitations a good workaround would be at least to allow sub-folder file managmeent so that we could create sub-folders with max 100 files each.

**Comment by trutypesounds** [comment]
mentioned many time here and there

**Comment by Jacknametrouble** [comment]
This is mentioned in the manual.

**Comment by imehesz** [comment]
Thanks for the reply  @Jacknametrouble 

> This is mentioned in the manual.

Yes it is, but it doesn't mean Polyend can't improve on it. And they really should. (I'll submit another ticket as a feature request)

thanks,
