### ISSUE TITLE
Copying instruments and patterns between projects

### ISSUE THREAD

**Issue by arphex** [polyend/TrackerIssues#1266]
Apologies if this was mentioned before (from a bit of searching nothing came up) and thanks for the great work on the tracker

Would be great if we could copy and paste instruments or patterns/tracks from one project to another.  Not sure if there is a way to 'hack' this (i.e. copying instrument wavs from one project to another on the sd card), but even if this works it wouldn't copy over the instrument parameters and would be a bit tedious.  Of course one can render a track and just re-use it but its not really what I`m looking for here.

All these are possible within a project, so would be great to extend this functionality between projects.  Even better if one could load instruments from another project without even opening it.

**Comment by jonwaterschoot** [comment]
Upon answering this question on lines I came looking for this over here on Github. I'll just copy paste my answer from there. 

> https://llllllll.co/t/polyend-tracker/30124/658

I just checked and instead of rendering an instrument into a wav file, there is a non-destructive workaround: you can copy the instrument outside the Tracker. 
An instrument is made with two files, the sample (.wav) and its settings (.mti). Copy the *.mti file and the *.wav to the other projects respective folders: "instruments" and "samples" 

So, step by step:

**1. On the Tracker:**
* First open the project containing the instrument you want to copy
* Check the number it has in the list of instruments
* (Start a new project and save it) 

**2. Shut down the Tracker and remove SD card**
* On a computer navigate to the original projects folder and look for the instrument you wish to copy:  SDcard > Projects > "Your Original Project" > instruments > xx.mti
* Copy the xx.mti file with your instruments number
* Paste this file in the new or other projects instrument folder
* Repeat for the wav file. in the samples folder

The mti file contains all the settings of the instrument, its file name is e.g. 14.mti
The wav file gets renamed to a two digit number e.g.: 14.wav
When you open your new project on the Tracker you'll see that the instrument still has the title derived from the original sample wav file

I have tested this with a free instrument "slot", in my case 14. I don't know if renaming the files to a different number would work.
 
While I'm sure I might be missing some complexities to program this, you'd think it would be doable to implement this. In the sample loader you'd navigate to the project containing the instrument and there be able to import the *.mti file. This would then of course also have to locate the sample and copy it as well. I'll see if I can suggest this feature e.g. on Github.

**Comment by tfspsound** [comment]
Nice one for even trying this. It’s a bit clunky but it’s better than nothing. An on device solution would be nice as sometimes I make a great sound in a project that it doesn’t suit just by getting side tracked but then it’s ‘locked’ inside that project. Cheers @jonwaterschoot

**Comment by bambrose** [comment]
This would open up the whole workflow so much (being done 'inside' the machine)
After I have spent 1/2 finding the perfect loop point on a string sample I really don't want to repeat the process,
Over time you could rely more and more on preset 'instrument files' rather than browsing the sample folder and having to create from scratch each time.
For me it's the biggest disappointment about the project as a whole that this function is likely never gong to materialise.
If it was even half and half (i.e. instruments can only be created 'offline' but can be loaded from a designated folder) it would be a massive enhancement

**Comment by Jacknametrouble** [comment]
This has been added in the newest 1.5b1 beta.

**Comment by bambrose** [comment]
Yes ! I saw that. Fantastic news. Thanks to all at polyend for continuing to work hard on improving the tracker and listening to your customers too (although I think you’d probably had this on the roadmap from there start) nonetheless. Massively appreciated

**Comment by jonwaterschoot** [comment]
Yay! Glad to see this added. Added this update to my post that was cross-referenced on the[ lines forum](https://llllllll.co/t/polyend-tracker/30124/669).
