### ISSUE TITLE
[1.1.21] The preview volume of sample loader is a little too loud for the sound of pattern playback.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#190]
I posted this issue as a feature request for # 186, but after that I reconsidered that it was as influential as a bug. I also received a message with the same opinion. So I reposted this issue as a bug report. Sorry for your inconvenience, but could you consider adjusting this issue and delete the post that was judged to be inappropriate?

* How often does this bug happen? (every time)

* Does this bug happen in previous firmware versions?（It also happens in 1.1.20）

* Does this bug happen in every project?（yes）

**Comment by MegaTurrican** [comment]
@andrzejmagierski2 @Jacknametrouble This bug is still present in 1.1.22 The preview volume of the samples is still high compared to the pattern; it should go back to the preview volume on previous firmwares before the dB introduction - or it should be proportional to the master volume. If you have a quiet track that you need to have the master volume all the way up, the sample preview will kill your speakers in the latest firmwares with dB values.

**Comment by modmodmodmod** [comment]
I agree.  Polyend once fixed this problem, and it was a little better than before, so I couldn't say it.  Thank you.

**Comment by Jacknametrouble** [comment]
Notice that the volume of samples recorded from any external source or FM radio is always on the exact same level as the original source (plus Gain). But their payback volume depends on factors as the volume set in Instrument Parameters and the track volume from Master section mixer.

**Comment by geoffreyclaret** [comment]
fixed? Preview volume is still too lound in 1.2.2 and 1.3 betas.. Is the worst issue for me at the moment..

**Comment by trutypesounds** [comment]
this is still in 1.4.0!
@ambv

**Comment by NoMoreFreezesPls** [comment]
ITS SO LOUD!!!!!!!!!!!!!
