### ISSUE TITLE
Low and highpass filters for delay and reverb

### ISSUE THREAD

**Issue by OnevenHub** [polyend/TrackerIssues#274]
Would love more control over the reverb and delay. I think a simple high and lowpass filter would really help fine tuning the effects.

**Comment by deixic** [comment]
I agree, and have also proposed this (closed issue #248).
Unfortunately, I think Polyend mistakenly thought of my request as per-send, instead of global.
I really hope they implement this, because without it the Reverb and Delay have limited use in a professional studio, and a Master EQ will not fix the problem of low-end buildup in the Reverb and Delay without also affecting the entire mix.
Here is a possible implementation idea:
(signal flow = instrument send > global Reverb HPF/LPF > Reverb > Master output):
![Reverb](https://user-images.githubusercontent.com/72669923/97092791-b7d38780-15fb-11eb-99f7-0159ca5ecd0f.jpg)
![Delay](https://user-images.githubusercontent.com/72669923/97092794-bace7800-15fb-11eb-91fe-611c6f135fdc.jpg)
https://www.youtube.com/watch?v=VhpwM8EoUPY

**Comment by smt923** [comment]
hope this could be implemented, helps to mix delay/reverb and also gives more possibilites with the sound, would be really useful to  have this
