### ISSUE TITLE
2.0 Unable to export Stems/Song/Pattern

### ISSUE THREAD

**Issue by ttiill** [polyend/TrackerIssues#345]
![IMG_5741](https://user-images.githubusercontent.com/74245221/98671303-55e18480-2354-11eb-8a02-3c08f9998d51.jpg)

It didnt happen before it suddenly appeared. But now it seems to be the case for all Projects. In the previous Firmware i did not have this problem but it did not appear after the update to 2.0. 

Thank you for the support so far 👍

**Comment by jaap3** [comment]
Assuming you've experienced this issue with firmware 1.2.0 (since there is no version 2.0). Please consider upgrading to firmware version 1.3.0. From what I've read song exporting has been rewritten, so the issue you had might be fixed. Please note that exporting songs can take a very long time, so please be patient when doing so.

**Comment by shuler323** [comment]
@jaap3 is right, other problems with exporting please write in existing open issues
