### ISSUE TITLE
Please open source the firmware. Would love to help out with some issues (and also load in some custom DSP)

### ISSUE THREAD

**Issue by cmorgan** [polyend/TrackerIssues#379]
Have you guys thought about open sourcing the firmware?

Would love to hack around on the Tracker. 
Keen to explore if it would be possible to add in custom effects into the audio pipeline.
Cheers for this awesome bit of tech!

**Comment by vitodsk** [comment]
I asked the question about the firmware. Looks there are no plans to release it as open source.

**Comment by CV-Gate** [comment]
I really second this. I think that it will not only benefit the users. Open sourcing a project like this can bump popularity dramatically. It also makes a difference between big companies' policies, which rarely will do. There are many stories of success, for example, Mutable Instruments.

**Comment by eclectocrat** [comment]
Yes, I don't think that there is any competitive harm since trackers are not exactly secret sauce, your great triumph is the software and hardware together. I've written my own sequencers for Novation's Launchpad Pro (which is open source and one of the most popular live control surface on the market), and would love to fix bugs and contribute my own ideas to this wonderful piece of engineering.
