### ISSUE TITLE
1.3.0 Can't get NTRQ to run in NES emulator

### ISSUE THREAD

**Issue by ilambert** [polyend/TrackerIssues#578]
I know it's technically not a bug, and I know it's not an advertised feature, but the tracker nerd in me wanted this to work so badly. 

Would be interesting for someone with debugging access to figure what the problem might be ;)

**Comment by mFoxRU** [comment]
First of all, I really appreciate that you added this feature. But it would be great if you improve this feature a little bit.

PULSAR doesn't work either and show this
![image](https://user-images.githubusercontent.com/5925970/103137836-b434ad80-46dd-11eb-9bf2-690a7945267a.png)

**Comment by mFoxRU** [comment]
@ilambert For now you can try cajoNES, it seems to work fine
![image](https://user-images.githubusercontent.com/5925970/103138001-10e49800-46df-11eb-90bf-cdb628368825.png)

**Comment by Djeroek** [comment]
Hah running a tracker inside the tracker, how meta :)

Don't want to start a new topic, but seeing this is a thread on the nes implementation; currently I think the games list is limited to 100 entries, I guess the same like with the samples folders in the beginning. Only the games folder isn't automatically split into >1 folder when the file count exceeds 100 files afaics. Would be cool if it does for the games list as well! Also, what are the A & B options for in the same screen you can load games? Don't seem to do anything here. 

One more improvement imo would be a button combo to reset back to the game list view instead of having to reset using the power button.

**Comment by jaap3** [comment]
@Djeroek please do open a new ticket, it's much easier for the developers to track one specific thing per "topic".

About the A&B options in the Games screen, I think they just serve as a hint/reminder for where the A/B buttons are when playing a game.

**Comment by XANi** [comment]
Tested on FF3 (english translation from vimm.net), froze tracker in intro. And the intro sounded so nice when ran thru chorus on my mixer... which made me think, sampling the game I currently play would be *pretty* cool

**Comment by tfspsound** [comment]
I know it’s a bit off topic but any suggestions for good safe ROM sites?
