### ISSUE TITLE
[1.3.0] Root note question

### ISSUE THREAD

**Issue by phaelam** [polyend/TrackerIssues#643]
I have a MIDI note set C5, is showing up in my MIDI monitor as C3.

why?

**Comment by loktez** [comment]
Same for me ( Ableton Live...) 
So the max could be G12?
 my best

**Comment by Jacknametrouble** [comment]
This is probably the matter of the used MIDI convention.

**Comment by piotr3500** [comment]
It's not technically a bug but rather a convention.
https://www.midi.org/forum/830-midi-octave-and-note-numbering-standard

Either way, we decided to make it configurable.

**Comment by sastani** [comment]
I believe this is the same as my issue...every note is two octaves off. I would consider this a bug, because of the following:

If I connect an external synth to Tracker’s MIDI in and out, then play C3 on an external synth in “live mode”, during playback it will actually trigger C5. Likewise, if I played F#5 it would playback F#7.

**Comment by ambv** [comment]
Fixed in 1.4.0b1.
