### ISSUE TITLE
[1.1.17] Tracker audio is 16ms behind other synced devices when either master or slave

### ISSUE THREAD

**Issue by splitradix** [polyend/TrackerIssues#92]
### Steps to reproduce

Sync the Tracker to any other midi device via midi clock and the Tracker's audio will play approximately 16ms behind the other devices. This happens when it is either the master or the slave to midi clock.

### Other important information

* How often does this bug happen? Every time.

* Does this bug happen in previous firmware versions? Yes, in all other firmware versions tested so far.

* Does this bug happen in every project? Yes.

**Comment by Jacknametrouble** [comment]
This is a known thing. A latency compensation option will be introduced in the major MIDI update later on the current year.

**Comment by rpc9943** [comment]
Good to know it is going to be fixed, when I read the update I thought it fixed latency!

**Comment by bnckd** [comment]
same problem here, midi alone runs supertight but as soon as i have samples running as well it's a mess. any news on that major midi update? since summer i can only use the tracker for either midi sequencing or standalone, which is unfortunate, as it was supposed to replace drummachines and sequence modular drums at the same time.

**Comment by shuler323** [comment]
try 1.3.0b4, it has implemented first sync delay compensation in PT
